baseurl = "https://mcguinlu.netlify.app/"
languageCode = "en-us"
title = "Note To Self"
theme = "tuftesque"
googleAnalytics = "G-YKRC772GWB"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/mcguinlu"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/mcguinlu"
    
[params]
    description = "A website built through Hugo and blogdown."
    showtitle = ""

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"
    
    backgroundColor = "#eeeeee"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    