---
title: Do blurbs predict whether films will pass the Bechdel test?
author: Luke McGuinness
date: '2021-04-12'
slug: do-blurbs-predict-whether-films-will-pass-the-bechdel-test
categories:
  - tidymodels
  - prediction
  - machine learning
  - R
  - side-project
tags: []
excerpt: Put excerpt here
math: no
meta: yes
draft: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
source(here::here("R","sidenote.R"))
```

## Install relevant pacakges



## Load the data

```{r}
library(tidyverse)
library(tidytext)

tuesdata <- tidytuesdayR::tt_load('2021-03-09')

movies <- tuesdata$movies %>%
  select(title, plot, binary) %>%
  filter(!is.na(plot) & !is.na(binary)) %>%
  mutate(text = plot) %>%
  select(-plot)
  
movies %>%
  unnest_tokens(word, text) %>%
  count(title, name = "total_words") %>%
  ggplot(aes(total_words)) +
  geom_histogram(fill = "midnightblue", alpha = 0.8)

```

### Build a model

```{r}
library(tidymodels)

set.seed(42)
review_split <- initial_split(movies, strata = binary)
review_train <- training(review_split)
review_test <- testing(review_split)
```


```{r}
library(textrecipes)
library(stopwords)

review_rec <- recipe(binary ~ text, data = review_train) %>%
  step_tokenize(text) %>%
  step_stopwords(text) %>%
  step_tokenfilter(text, max_tokens = 500) %>%
  step_tfidf(text) %>%
  step_normalize(all_predictors())

review_prep <- prep(review_rec)

review_prep

```

###

```{r}
lasso_spec <- logistic_reg(penalty = tune(), mixture = 1) %>%
  set_engine("glmnet")

lasso_wf <- workflow() %>%
  add_recipe(review_rec) %>%
  add_model(lasso_spec)

lasso_wf
```


`r tufte::margin_note("You may need the development version of <code>recipes</code> for this to work, as per [this issue](https://github.com/tidymodels/tune/issues/192)")`

```{r}
lambda_grid <- grid_regular(penalty(), levels = 40)

set.seed(42)
review_folds <- bootstraps(review_train, strata = binary)
review_folds

doParallel::registerDoParallel()

set.seed(2020)
lasso_grid <- tune_grid(
  lasso_wf,
  resamples = review_folds,
  grid = lambda_grid,
  metrics = metric_set(roc_auc, ppv, npv)
)

lasso_grid %>%
  collect_metrics()
```
